/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamRouteImport } from './routes/_exam'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetupPasswordRouteImport } from './routes/auth/setup-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSectionsIndexRouteImport } from './routes/_app/sections/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppTestsResultsAttemptIdRouteImport } from './routes/_app/tests/results/$attemptId'
import { Route as AppSectionsSlugPreviewRouteImport } from './routes/_app/sections/$slug/preview'
import { Route as ExamSectionsSlugAttemptAttemptIdRouteImport } from './routes/_exam/sections/$slug/attempt/$attemptId'

const ExamRoute = ExamRouteImport.update({
  id: '/_exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupPasswordRoute = AuthSetupPasswordRouteImport.update({
  id: '/auth/setup-password',
  path: '/auth/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionsIndexRoute = AppSectionsIndexRouteImport.update({
  id: '/sections/',
  path: '/sections/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTestsResultsAttemptIdRoute =
  AppTestsResultsAttemptIdRouteImport.update({
    id: '/tests/results/$attemptId',
    path: '/tests/results/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSectionsSlugPreviewRoute = AppSectionsSlugPreviewRouteImport.update({
  id: '/sections/$slug/preview',
  path: '/sections/$slug/preview',
  getParentRoute: () => AppRoute,
} as any)
const ExamSectionsSlugAttemptAttemptIdRoute =
  ExamSectionsSlugAttemptAttemptIdRouteImport.update({
    id: '/sections/$slug/attempt/$attemptId',
    path: '/sections/$slug/attempt/$attemptId',
    getParentRoute: () => ExamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sections/': typeof AppSectionsIndexRoute
  '/sections/$slug/preview': typeof AppSectionsSlugPreviewRoute
  '/tests/results/$attemptId': typeof AppTestsResultsAttemptIdRoute
  '/sections/$slug/attempt/$attemptId': typeof ExamSectionsSlugAttemptAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports': typeof AppReportsIndexRoute
  '/sections': typeof AppSectionsIndexRoute
  '/sections/$slug/preview': typeof AppSectionsSlugPreviewRoute
  '/tests/results/$attemptId': typeof AppTestsResultsAttemptIdRoute
  '/sections/$slug/attempt/$attemptId': typeof ExamSectionsSlugAttemptAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_exam': typeof ExamRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sections/': typeof AppSectionsIndexRoute
  '/_app/sections/$slug/preview': typeof AppSectionsSlugPreviewRoute
  '/_app/tests/results/$attemptId': typeof AppTestsResultsAttemptIdRoute
  '/_exam/sections/$slug/attempt/$attemptId': typeof ExamSectionsSlugAttemptAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/admin/users'
    | '/api/auth/$'
    | '/reports/'
    | '/sections/'
    | '/sections/$slug/preview'
    | '/tests/results/$attemptId'
    | '/sections/$slug/attempt/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/admin/users'
    | '/api/auth/$'
    | '/reports'
    | '/sections'
    | '/sections/$slug/preview'
    | '/tests/results/$attemptId'
    | '/sections/$slug/attempt/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_exam'
    | '/_app/admin'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/setup-password'
    | '/_app/admin/users'
    | '/api/auth/$'
    | '/_app/reports/'
    | '/_app/sections/'
    | '/_app/sections/$slug/preview'
    | '/_app/tests/results/$attemptId'
    | '/_exam/sections/$slug/attempt/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ExamRoute: typeof ExamRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetupPasswordRoute: typeof AuthSetupPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_exam': {
      id: '/_exam'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-password': {
      id: '/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sections/': {
      id: '/_app/sections/'
      path: '/sections'
      fullPath: '/sections/'
      preLoaderRoute: typeof AppSectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/tests/results/$attemptId': {
      id: '/_app/tests/results/$attemptId'
      path: '/tests/results/$attemptId'
      fullPath: '/tests/results/$attemptId'
      preLoaderRoute: typeof AppTestsResultsAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sections/$slug/preview': {
      id: '/_app/sections/$slug/preview'
      path: '/sections/$slug/preview'
      fullPath: '/sections/$slug/preview'
      preLoaderRoute: typeof AppSectionsSlugPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_exam/sections/$slug/attempt/$attemptId': {
      id: '/_exam/sections/$slug/attempt/$attemptId'
      path: '/sections/$slug/attempt/$attemptId'
      fullPath: '/sections/$slug/attempt/$attemptId'
      preLoaderRoute: typeof ExamSectionsSlugAttemptAttemptIdRouteImport
      parentRoute: typeof ExamRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSectionsIndexRoute: typeof AppSectionsIndexRoute
  AppSectionsSlugPreviewRoute: typeof AppSectionsSlugPreviewRoute
  AppTestsResultsAttemptIdRoute: typeof AppTestsResultsAttemptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSectionsIndexRoute: AppSectionsIndexRoute,
  AppSectionsSlugPreviewRoute: AppSectionsSlugPreviewRoute,
  AppTestsResultsAttemptIdRoute: AppTestsResultsAttemptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ExamRouteChildren {
  ExamSectionsSlugAttemptAttemptIdRoute: typeof ExamSectionsSlugAttemptAttemptIdRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamSectionsSlugAttemptAttemptIdRoute: ExamSectionsSlugAttemptAttemptIdRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ExamRoute: ExamRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetupPasswordRoute: AuthSetupPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
